---
# handlers file for common-webserver
# handlers/main.yml
- name: Restart nginx
  ansible.builtin.service:
    name: "{{ nginx_service_name | default('nginx') }}"
    state: restarted
  become: true
